# Generated by Django 5.0.4 on 2024-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzdrowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionx', models.FloatField()),
                ('positiony', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
