# Generated by Django 5.0.4 on 2024-04-11 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzdrowisko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzdrowisko',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain Polish characters and spaces', regex='^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='uzdrowisko',
            name='image',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Name can only contain Polish characters and spaces', regex='^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='uzdrowisko',
            name='link',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Name can only contain Polish characters and spaces', regex='^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='uzdrowisko',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain Polish characters and spaces', regex='^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='uzdrowisko',
            name='phoneNumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name can only contain Polish characters and spaces', regex='^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ0-9 ]+$')]),
        ),
    ]
