# Generated by Django 5.0.4 on 2024-04-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzdrowisko', '0004_alter_uzdrowisko_address_alter_uzdrowisko_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='place',
            new_name='uzdrowisko',
        ),
        migrations.AddField(
            model_name='uzdrowisko',
            name='details',
            field=models.CharField(default='details', max_length=2000),
            preserve_default=False,
        ),
    ]
